const pptxgen =
    require("pptxgenjs");

const fs =
    require("fs");

const path =
    require("path");

const analytics =
    require("../analytics");

const {
    formatINR
} = require("../../utils/money");

// --------------------------------------------------
// GENERATE WEEKLY SALES DECK
// --------------------------------------------------

function generateSalesDeck() {

    const data = analytics.getWeeklySummary();

    const pptx = new pptxgen();

    pptx.layout = "LAYOUT_WIDE";

    pptx.author = "Kirana Store Agent";
    pptx.subject = "Weekly Sales Analysis";
    pptx.title = "Weekly Sales Analysis";
    pptx.company = "Kirana Store";


    // ----------------------------------------------
    // OUTPUT
    // ----------------------------------------------

    const outputDir = path.join(
        process.cwd(),
        "generated"
    );

    fs.mkdirSync(
        outputDir,
        {
            recursive: true
        }
    );

    const filename =
        `sales-analysis-${data.endDate}.pptx`;

    const filePath =
        path.join(
            outputDir,
            filename
        );


    // ----------------------------------------------
    // SAFE NUMBER FUNCTION
    // ----------------------------------------------

    function num(value) {

        if (typeof value === "number") {
            return Number.isFinite(value) ? value : 0;
        }

        if (value === null || value === undefined) {
            return 0;
        }

        const cleaned =
            String(value)
                .replace(/[₹,\s]/g, "");

        const result = Number(cleaned);

        return Number.isFinite(result)
            ? result
            : 0;
    }


    // ----------------------------------------------
    // SLIDE 1 — TITLE
    // ----------------------------------------------

    let slide = pptx.addSlide();

    slide.addText(
        "Weekly Sales Analysis",
        {
            x: 0.7,
            y: 1.5,
            w: 12,
            h: 0.7,
            fontSize: 30,
            bold: true,
            align: "center"
        }
    );

    slide.addText(
        `${data.startDate} → ${data.endDate}`,
        {
            x: 0.7,
            y: 2.4,
            w: 12,
            h: 0.4,
            fontSize: 16,
            align: "center"
        }
    );

    slide.addText(
        "Generated by Supermarket Ops Agent",
        {
            x: 0.7,
            y: 3.2,
            w: 12,
            h: 0.4,
            fontSize: 12,
            align: "center"
        }
    );


    // ----------------------------------------------
    // CALCULATE TOTALS
    // ----------------------------------------------

    let totalSales = 0;
    let totalBills = 0;
    let totalCGST = 0;
    let totalSGST = 0;

    for (const day of data.sales || []) {

        totalSales += num(day.sales);

        totalBills += num(day.bills);

        totalCGST += num(day.cgst);

        totalSGST += num(day.sgst);
    }


    // ----------------------------------------------
    // SLIDE 2 — KPI
    // ----------------------------------------------

    slide = pptx.addSlide();

    slide.addText(
        "Weekly Performance",
        {
            x: 0.6,
            y: 0.4,
            w: 12,
            h: 0.5,
            fontSize: 24,
            bold: true
        }
    );


    const avgBill =
        totalBills > 0
            ? totalSales / totalBills
            : 0;


    const kpis = [

        [
            "Total Sales",
            formatINR(totalSales)
        ],

        [
            "Bills",
            String(totalBills)
        ],

        [
            "Average Bill",
            formatINR(avgBill)
        ],

        [
            "GST Collected",
            formatINR(
                totalCGST + totalSGST
            )
        ]

    ];


    let x = 0.7;

    for (const [label, value] of kpis) {

        slide.addText(
            label,
            {
                x,
                y: 1.5,
                w: 2.6,
                h: 0.4,
                fontSize: 14,
                bold: true,
                align: "center"
            }
        );

        slide.addText(
            value,
            {
                x,
                y: 2.1,
                w: 2.6,
                h: 0.6,
                fontSize: 24,
                bold: true,
                align: "center"
            }
        );

        x += 3;
    }


    // ----------------------------------------------
    // SLIDE 3 — SALES CHART
    // ----------------------------------------------

    slide = pptx.addSlide();

    slide.addText(
        "Daily Sales",
        {
            x: 0.6,
            y: 0.4,
            w: 12,
            h: 0.5,
            fontSize: 24,
            bold: true
        }
    );


    const salesChartData = [

        {
            name: "Sales",

            labels:
                (data.sales || []).map(
                    day => day.date
                ),

            values:
                (data.sales || []).map(
                    day => num(day.sales) / 100
                )
        }

    ];


    slide.addChart(
        pptx.ChartType.line,
        salesChartData,
        {
            x: 0.8,
            y: 1.3,
            w: 11.5,
            h: 5.2,

            catAxisLabelFontSize: 10,
            valAxisLabelFontSize: 10,

            showLegend: false,
            showTitle: false,

            valAxisTitle: "Sales (₹)",

            catAxisTitle: "Date"
        }
    );


    // ----------------------------------------------
    // SLIDE 4 — TOP PRODUCTS
    // ----------------------------------------------

    slide = pptx.addSlide();

    slide.addText(
        "Top Selling Products",
        {
            x: 0.6,
            y: 0.4,
            w: 12,
            h: 0.5,
            fontSize: 24,
            bold: true
        }
    );


    const topProducts =
        (data.topProducts || []).slice(0, 10);


    const productChartData = [

        {
            name: "Units Sold",

            labels:
                topProducts.map(
                    product =>
                        product.product_name
                ),

            values:
                topProducts.map(
                    product =>
                        num(product.quantity_sold)
                )
        }

    ];


    slide.addChart(
        pptx.ChartType.bar,
        productChartData,
        {
            x: 0.7,
            y: 1.2,
            w: 11.6,
            h: 5.4,

            showLegend: false,

            catAxisLabelFontSize: 9,
            valAxisLabelFontSize: 9
        }
    );


    // ----------------------------------------------
    // SLIDE 5 — GST
    // ----------------------------------------------

    slide = pptx.addSlide();

    slide.addText(
        "GST Summary",
        {
            x: 0.6,
            y: 0.4,
            w: 12,
            h: 0.5,
            fontSize: 24,
            bold: true
        }
    );


    const gst = data.gst || {};


    const taxableAmount =
        num(gst.taxable_amount);

    const cgst =
        num(gst.cgst);

    const sgst =
        num(gst.sgst);

    const totalTax =
        num(gst.total_tax);


    slide.addText(
        `Taxable Sales: ${formatINR(taxableAmount)}`,
        {
            x: 1,
            y: 1.5,
            w: 5,
            h: 0.5,
            fontSize: 18
        }
    );


    slide.addText(
        `CGST: ${formatINR(cgst)}`,
        {
            x: 1,
            y: 2.3,
            w: 5,
            h: 0.5,
            fontSize: 18
        }
    );


    slide.addText(
        `SGST: ${formatINR(sgst)}`,
        {
            x: 1,
            y: 3.1,
            w: 5,
            h: 0.5,
            fontSize: 18
        }
    );


    slide.addText(
        `Total GST: ${formatINR(totalTax)}`,
        {
            x: 1,
            y: 4,
            w: 5,
            h: 0.6,
            fontSize: 22,
            bold: true
        }
    );


    // ----------------------------------------------
    // SLIDE 6 — STOCK HEALTH
    // ----------------------------------------------

    slide = pptx.addSlide();

    slide.addText(
        "Stock Health",
        {
            x: 0.6,
            y: 0.4,
            w: 12,
            h: 0.5,
            fontSize: 24,
            bold: true
        }
    );


    const totalProducts =
        num(data.stock?.totalProducts);

    const lowStockCount =
        num(data.stock?.lowStockCount);

    const outOfStockCount =
        num(data.stock?.outOfStockCount);


    slide.addText(
        `Total products: ${totalProducts}`,
        {
            x: 1,
            y: 1.5,
            w: 6,
            h: 0.5,
            fontSize: 18
        }
    );


    slide.addText(
        `Low stock: ${lowStockCount}`,
        {
            x: 1,
            y: 2.3,
            w: 6,
            h: 0.5,
            fontSize: 18
        }
    );


    slide.addText(
        `Out of stock: ${outOfStockCount}`,
        {
            x: 1,
            y: 3.1,
            w: 6,
            h: 0.5,
            fontSize: 18
        }
    );


    // ----------------------------------------------
    // SLIDE 7 — INSIGHTS
    // ----------------------------------------------

    slide = pptx.addSlide();

    slide.addText(
        "Key Insights",
        {
            x: 0.6,
            y: 0.4,
            w: 12,
            h: 0.5,
            fontSize: 24,
            bold: true
        }
    );


    const insights = [];


    if (topProducts.length > 0) {

        insights.push(
            `Top seller: ${topProducts[0].product_name}`
        );

    }


    if (totalBills > 0) {

        insights.push(
            `Average bill value: ${formatINR(avgBill)}`
        );

    }


    if (lowStockCount > 0) {

        insights.push(
            `${lowStockCount} products need restocking`
        );

    }


    if (outOfStockCount > 0) {

        insights.push(
            `${outOfStockCount} products are out of stock`
        );

    }


    if (insights.length === 0) {

        insights.push(
            "Not enough sales data to generate insights."
        );

    }


    slide.addText(
        insights
            .map(
                insight => `• ${insight}`
            )
            .join("\n\n"),
        {
            x: 1,
            y: 1.5,
            w: 10.5,
            h: 4,
            fontSize: 20,
            breakLine: false
        }
    );


    // ----------------------------------------------
    // WRITE FILE
    // ----------------------------------------------

    return pptx.writeFile({
        fileName: filePath
    }).then(
        () => ({
            success: true,
            filePath,
            filename
        })
    );
}

module.exports = {
    generateSalesDeck
};